### ISSUE TITLE
Server will no start: `"ts-node" exec not found`

### ISSUE THREAD

**Issue by cedric25** [hellokvn/medium-typescript-boilerplate#1]
After `npm install` and `npm run dev`, I get this error:

<img width="996" alt="Screenshot 2022-03-09 at 09 40 49" src="https://user-images.githubusercontent.com/4280765/157404465-a1460d67-4d05-4cc4-8438-405291020e55.png">

It looks like `nodemon` explicitly needs `ts-node` to be installed.

`npm i ts-node -D` fixed the problem for me.
It might be necessary **to list it as a dev dependency**?

**Comment by hellokvn** [comment]
Hi @cedric25,

You are right! I have forgotten to install ts-node. Yes, you have to install it as a dev dependency. Thank you for pointing this out. It worked for me because I had installed ts-node globally. I going to update my article and this repository.

**Comment by cedric25** [comment]
> because I had installed `ts-node` globally

That's what I thought yes :)
